### ISSUE TITLE
OOM 问题

### ISSUE THREAD

**Issue by UltramanKuz** [lsdefine/simple_GRPO#11]
请问多大的内存才能运行grpo_ref_split.py。我将参数num_pre_Q设置为8，使用A100 40G跑Qwen2.5-3B模型会OOM，如果将num_pre_Q设置为2还是OOM

`model_path = "Qwen/Qwen2.5-3B-Instruct"
beta = 0.04
num_pre_Q = 2
Q_batch_size = 1
all_steps = 1000
max_prompt_length = 400
save_steps = 200

ds_config = {
    "train_micro_batch_size_per_gpu": Q_batch_size*num_pre_Q,
    "gradient_accumulation_steps": 2,
    "optimizer": {
        "type": "AdamW",
        "params": { "lr": 1e-6 }
    },
    "bf16": {"enabled": True},
    "zero_optimization": {
        "stage": 2,
        "allgather_partitions": True,
        "allgather_bucket_size": 2e8,
        "overlap_comm": True,
        "reduce_scatter": True,
        "reduce_bucket_size": 2e8,
        "contiguous_gradients": True,
        "stage3_gather_16bit_weights_on_model_save": True,
        "offload_optimizer": {"device": "cpu"}
    }
}`

最后的报错：
[rank3]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.61 GiB. GPU  has a total capacity of 39.39 GiB of which 1.52 GiB is free. Process 72820 has 37.86 GiB memory in use. Of the allocated memory 35.04 GiB is allocated by PyTorch, and 1.34 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by UltramanKuz** [comment]
通过设置环境变量解决了

**Comment by GaussRieman** [comment]
> 通过设置环境变量解决了

请问怎么解决的？

**Comment by UltramanKuz** [comment]
> > 通过设置环境变量解决了
> 
> 请问怎么解决的？

试一下export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True，这样可以尽可能提高num_pre_Q。我用A100 40G 训练Qwen2.5-3B的时候num_pre_Q可以提高到6，8会OOM，可能会影响训练质量

**Comment by swordqiqi** [comment]
> PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

您好，您分别使用了几张A100训练3B和7B模型？

**Comment by swordqiqi** [comment]
> > > PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
> > 
> > 
> > 您好，您分别使用了几张A100训练3B和7B模型？
> 
> 我是一张卡推理服务，两张卡训练3B模型，参数num_pre_Q = 6，设置为8会OOM，7B可能需要更大显存的卡，暂时没有尝试

好的好的，非常感谢您！

**Comment by feiyang-k** [comment]
> > > 通过设置环境变量解决了
> > 
> > 
> > 请问怎么解决的？
> 
> 试一下export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True，这样可以尽可能提高num_pre_Q。我用A100 40G 训练Qwen2.5-3B的时候num_pre_Q可以提高到6，8会OOM，可能会影响训练质量

This is helpful! 我用的8卡的80G H100，之前是save model的时候7B的model会OOM，加上这个之后就没事了。感谢！把这个写到英文的readme里吧
